[package]
name = "data-driver-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
dlmalloc = "0.2"
rkyv = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
